{% set name = "browserforge" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/browserforge-{{ version }}.tar.gz
  sha256: 7036d73fb066a4361a015b619079474c42d8b0ff415e1d874b62366de48d0b61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - click
    - typing_extensions
  run_constrained:
    - orjson *

test:
  imports:
    - browserforge
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/daijro/browserforge
  summary: Intelligent browser header & fingerprint generator
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
